# spring.datasource.url=jdbc:postgresql://localhost:5432/ecommercedb
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_shop
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.h2.console.enabled=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Configuration Redis
spring.redis.host=localhost
spring.redis.port=6379
# spring.redis.password=votre_mot_de_passe  # Si vous avez un mot de passe
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000     # TTL en millisecondes (1 heure) 