vault.uri=http://localhost:8200
vault.token=${VAULT_DEV_TOKEN}
secret.rotation.jwt.cron=0 0 1 * * *
notification.admin.email=admin-dev@company.com
notification.slack.webhook=${SLACK_WEBHOOK_DEV}

# JPA Configuration spécifique au dev
spring.jpa.hibernate.ddl-auto=update

# Redis Configuration simple pour développement
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=dev123
spring.redis.ssl=false
spring.redis.timeout=1000

# Configuration du pool de connexions
spring.redis.lettuce.pool.max-active=4
spring.redis.lettuce.pool.max-idle=4
spring.redis.lettuce.pool.min-idle=2
spring.redis.lettuce.pool.max-wait=-1ms