# spring.datasource.url=jdbc:postgresql://localhost:5432/ecommercedb
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver

# Supabase Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=${JWT_SECRET}


# SSL Configuration for Supabase (required)
spring.datasource.hikari.ssl-mode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.h2.console.enabled=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
# spring.redis.password=your_password  
spring.cache.redis.time-to-live=3600000     

# Redis Cluster Configuration
spring.redis.cluster.nodes=localhost:6379,localhost:6380,localhost:6381
spring.redis.cluster.max-redirects=3

# Caffeine Configuration
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=5m

# Cache Type
spring.cache.type=COMPOSITE

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# Custom Metrics
management.metrics.enable.all=true 

# DDOS Protection
server.tomcat.max-connections=10000
server.tomcat.accept-count=100
server.tomcat.max-threads=200
ddos.max-requests-per-minute=100 

# CORS Configuration
spring.mvc.cors.mapping=/**
spring.mvc.cors.allowed-origins=http://localhost:5173
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true
spring.mvc.cors.max-age=3600

# Default active profile
spring.profiles.active=dev